import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { describe, it } from 'node:test';

import {
  HOST_CLASSES,
  URL_KINDS,
  classifyUrl,
  kindForContentType,
  sitemapUrls,
} from '../scripts/lib/seo-url-taxonomy.mjs';
import { PAGE_FAMILIES } from '../scripts/seo-ai-visibility-scorecard.mjs';

const repoUrl = (relativePath) => new URL(`../${relativePath}`, import.meta.url);

const mainSitemapUrls = sitemapUrls(
  readFileSync(repoUrl('public/sitemap-main.xml'), 'utf8'),
);

// The blog and docs sitemaps are generated by Astro and Mintlify at build time
// and are not committed, so their URL shape is reconstructed from the sources
// that produce them. That keeps the "every sitemap URL maps to exactly one
// family" assertion honest for all three sitemaps in a bare checkout.
const blogSitemapUrls = [
  'https://www.worldmonitor.app/blog/',
  ...readdirSync(repoUrl('blog-site/src/content/blog'))
    .filter((name) => name.endsWith('.md') || name.endsWith('.mdx'))
    .map((name) => `https://www.worldmonitor.app/blog/${name.replace(/\.mdx?$/, '')}/`),
];

const docsSitemapUrls = [
  'https://www.worldmonitor.app/docs',
  ...readdirSync(repoUrl('docs'))
    .filter((name) => name.endsWith('.mdx'))
    .map((name) => `https://www.worldmonitor.app/docs/${name.replace(/\.mdx$/, '')}`),
  ...readdirSync(repoUrl('docs'))
    .filter((name) => name.endsWith('.mdx'))
    .slice(0, 5)
    .map((name) => `https://www.worldmonitor.app/docs/zh/${name.replace(/\.mdx$/, '')}`),
];

describe('seo url taxonomy', () => {
  it('parses every loc out of the committed root sitemap', () => {
    assert.ok(mainSitemapUrls.length > 200, `expected the root sitemap inventory, got ${mainSitemapUrls.length}`);
  });

  it('maps every sitemap URL to exactly one family and exactly one kind', () => {
    const allUrls = [...mainSitemapUrls, ...blogSitemapUrls, ...docsSitemapUrls];
    assert.ok(allUrls.length > 300, `expected all three sitemap inventories, got ${allUrls.length}`);
    const families = new Set();
    const kinds = new Set();
    for (const url of allUrls) {
      const classified = classifyUrl(url);
      assert.equal(
        typeof classified.family,
        'string',
        `${url} produced no family`,
      );
      assert.ok(
        PAGE_FAMILIES.includes(classified.family),
        `${url} mapped to unknown family ${classified.family}`,
      );
      assert.ok(
        URL_KINDS.includes(classified.kind),
        `${url} mapped to unknown kind ${classified.kind}`,
      );
      assert.equal(
        classified.familyMatches.length,
        1,
        `${url} matched ${classified.familyMatches.length} families: ${classified.familyMatches.join(', ')}`,
      );
      assert.equal(
        classified.kindMatches.length,
        1,
        `${url} matched ${classified.kindMatches.length} kinds: ${classified.kindMatches.join(', ')}`,
      );
      families.add(classified.family);
      kinds.add(classified.kind);
    }
    // The families the issue named must all be exercised by the real inventory,
    // otherwise the mapping is untested where it was added.
    for (const family of [
      'homepage',
      'dashboard',
      'blog',
      'documentation',
      'docs_zh',
      'country_pages',
      'chokepoints',
      'crises',
      'tools',
      'pricing',
      'developer_mcp',
      'sources',
      'compare',
      'research',
      'use_cases',
      'markdown_twins',
    ]) {
      assert.ok(families.has(family), `no sitemap URL exercised family ${family}`);
    }
    for (const kind of ['html', 'markdown-twin']) {
      assert.ok(kinds.has(kind), `no sitemap URL exercised kind ${kind}`);
    }
  });

  it('records a host dimension for apex and variant hosts', () => {
    assert.equal(classifyUrl('https://www.worldmonitor.app/').hostClass, 'www');
    assert.equal(classifyUrl('https://worldmonitor.app/mcp').hostClass, 'apex');
    assert.equal(
      classifyUrl('https://tech.worldmonitor.app/dashboard').hostClass,
      'variant',
    );
    assert.equal(
      classifyUrl('https://api.worldmonitor.app/openapi.json').hostClass,
      'variant',
    );
    for (const hostClass of new Set(
      [...mainSitemapUrls].map((url) => classifyUrl(url).hostClass),
    )) {
      assert.ok(HOST_CLASSES.includes(hostClass), `unknown host class ${hostClass}`);
    }
  });

  it('separates render subresources, data files and feeds from HTML', () => {
    assert.equal(
      classifyUrl('https://www.worldmonitor.app/docs/_next/static/chunks/main-abc123.js').kind,
      'subresource',
    );
    assert.equal(
      classifyUrl('https://www.worldmonitor.app/docs/_next/static/css/app.css').kind,
      'subresource',
    );
    assert.equal(
      classifyUrl('https://www.worldmonitor.app/api/openapi.json').kind,
      'data',
    );
    assert.equal(classifyUrl('https://www.worldmonitor.app/sitemap.xml').kind, 'feed');
    assert.equal(classifyUrl('https://www.worldmonitor.app/pricing.md').kind, 'markdown-twin');
    assert.equal(classifyUrl('https://www.worldmonitor.app/llms.txt').kind, 'markdown-twin');
    assert.equal(classifyUrl('https://www.worldmonitor.app/countries/france/').kind, 'html');
  });

  it('refuses an unmapped path instead of bucketing it as other', () => {
    assert.throws(
      () => classifyUrl('https://www.worldmonitor.app/totally-unmapped-surface/'),
      /does not map to a page family/,
    );
  });

  it('refuses a host outside the property', () => {
    assert.throws(
      () => classifyUrl('https://example.com/countries/france/'),
      /host/,
    );
  });
});

describe('URL taxonomy for rows Search Console reports', () => {
  it('files /favicon.ico with the site infrastructure', () => {
    assert.equal(classifyUrl('https://www.worldmonitor.app/favicon.ico').family, 'site_infrastructure');
  });

  it('says a first-party subdomain has no family, not that it is outside the property', () => {
    assert.throws(
      () => classifyUrl('https://status.worldmonitor.app/'),
      (error) => /status\.worldmonitor\.app/.test(error.message)
        && /no page family/.test(error.message)
        && !/outside/.test(error.message),
    );
    assert.throws(() => classifyUrl('https://example.com/'), /outside the worldmonitor\.app property/);
  });

  it('reads an SVG content type as a subresource, not a feed', () => {
    assert.equal(kindForContentType('image/svg+xml'), 'subresource');
    assert.equal(kindForContentType('application/rss+xml'), 'feed');
  });
});
