// Non-sebuf: returns XML/HTML, stays as standalone Vercel function
/**
 * Story Page for Social Crawlers
 * Returns HTML with proper og:image and twitter:card meta tags.
 * Twitter/Facebook/LinkedIn crawlers hit this, real users get redirected to the SPA.
 */

// Every country with a published /countries/<slug>/ corpus page, generated by
// scripts/generate-country-corpus-slugs.mjs from the same snapshot and the same
// slugify()/uniqueSlug() the corpus builder uses. It replaces a hand-written
// 20-code name table that left every other country titled by raw ISO2.
import { COUNTRY_CORPUS_NAMES, COUNTRY_CORPUS_SLUGS } from './_country-corpus-slugs.generated.js';

// Canonical www origin for indexable destinations. The share stub itself keeps
// serving from the bare-host api origin; only its canonical target moves.
const WWW_ORIGIN = 'https://www.worldmonitor.app';

const BOT_UA = /twitterbot|facebookexternalhit|linkedinbot|slackbot|telegrambot|whatsapp|discordbot|redditbot|googlebot/i;

export default function handler(req, res) {
  const url = new URL(req.url, 'https://worldmonitor.app');
  const countryCode = (url.searchParams.get('c') || '').toUpperCase();
  const type = url.searchParams.get('t') || 'ciianalysis';
  const ts = url.searchParams.get('ts') || '';
  const score = url.searchParams.get('s') || '';
  const level = url.searchParams.get('l') || '';

  const ua = req.headers['user-agent'] || '';
  const isBot = BOT_UA.test(ua);

  res.setHeader('Vary', 'User-Agent');

  const baseUrl = 'https://worldmonitor.app';
  const storyParams = new URLSearchParams({ c: countryCode, t: type });
  if (ts) storyParams.set('ts', ts);
  const dashboardUrl = `${WWW_ORIGIN}/dashboard`;
  const spaUrl = `${dashboardUrl}?${storyParams}`;

  // Real users → redirect to SPA
  if (!isBot) {
    res.writeHead(302, {
      Location: spaUrl,
      'Cache-Control': 'private, no-store',
    });
    res.end();
    return;
  }

  // Bots → serve meta tags
  const countryName = COUNTRY_CORPUS_NAMES[countryCode] || countryCode || 'Global';
  // Every share of a country carries a unique `ts`, so a /dashboard canonical
  // files each one as its own "Alternate page with proper canonical" against a
  // JS shell with no country content (#8604). Consolidate onto the corpus page
  // that actually ranks for "<country> instability" instead.
  const corpusSlug = COUNTRY_CORPUS_SLUGS[countryCode] || '';
  const corpusUrl = corpusSlug ? `${WWW_ORIGIN}/countries/${corpusSlug}/` : '';
  const canonicalUrl = corpusUrl || dashboardUrl;
  const title = `${countryName} Intelligence Brief | World Monitor`;
  const description = `Real-time instability analysis for ${countryName}. Country Instability Index, military posture, threat classification, and prediction markets. Free, open-source geopolitical intelligence.`;
  const imageParams = new URLSearchParams({ c: countryCode, t: type });
  if (score) imageParams.set('s', score);
  if (level) imageParams.set('l', level);
  const imageUrl = `${baseUrl}/api/og-story?${imageParams}`;
  const storyUrl = `${baseUrl}/api/story?${storyParams}`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(description)}"/>

  <meta property="og:type" content="article"/>
  <meta property="og:title" content="${esc(title)}"/>
  <meta property="og:description" content="${esc(description)}"/>
  <meta property="og:image" content="${esc(imageUrl)}"/>
  <meta property="og:image:width" content="1200"/>
  <meta property="og:image:height" content="630"/>
  <meta property="og:url" content="${esc(storyUrl)}"/>
  <meta property="og:site_name" content="World Monitor"/>

  <meta name="twitter:card" content="summary_large_image"/>
  <meta name="twitter:site" content="@WorldMonitorApp"/>
  <meta name="twitter:title" content="${esc(title)}"/>
  <meta name="twitter:description" content="${esc(description)}"/>
  <meta name="twitter:image" content="${esc(imageUrl)}"/>

  <link rel="canonical" href="${esc(canonicalUrl)}"/>
</head>
<body>
  <h1>${esc(title)}</h1>
  <p>${esc(description)}</p>
  <p><a href="${esc(spaUrl)}">View live analysis</a></p>${corpusUrl ? `
  <p><a href="${esc(corpusUrl)}">Read the full ${esc(countryName)} brief</a></p>` : ''}
</body>
</html>`;

  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=300, s-maxage=300, stale-while-revalidate=60');
  res.status(200).send(html);
}

function esc(str) {
  return str.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
